# Generated by Django 2.2 on 2019-10-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
