# Generated by Django 2.2 on 2019-10-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0005_auto_20191001_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mail', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Year',
            field=models.CharField(choices=[('1st', 'first'), ('2nd', 'second'), ('3rd', 'third'), ('4th', 'fourth'), ('HS or Lower', 'HS or Lower'), ('grad', 'Graduate'), ('PG', 'Post-Graduate')], max_length=13),
        ),
    ]
