# Generated by Django 2.2 on 2019-10-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0006_auto_20191002_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='mail',
            new_name='feedemail',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='feedname',
        ),
    ]
