# Generated by Django 2.2 on 2019-10-04 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0007_auto_20191002_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfileInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
