# Generated by Django 2.2 on 2019-10-08 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0008_auto_20191004_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedemail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='content',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedname',
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer_name',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='details',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='happy',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
