# Generated by Django 2.2 on 2019-10-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0009_auto_20191008_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='customer_name',
            new_name='name',
        ),
    ]
