# Generated by Django 2.2 on 2019-10-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0010_auto_20191008_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='details',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='happy',
        ),
    ]
