# Generated by Django 2.2 on 2019-11-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0014_userprofileinfo_varified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='varification_id',
            field=models.IntegerField(default=1245),
        ),
    ]
