# Generated by Django 2.2 on 2019-12-18 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0016_auto_20191216_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
