# Generated by Django 3.1.4 on 2020-12-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0017_post_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('in_link', models.URLField(blank=True)),
                ('fb_link', models.URLField(blank=True)),
                ('ln_link', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(upload_to='members/images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-event_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img'),
        ),
    ]
