# Generated by Django 3.1.5 on 2021-01-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0017_post_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-event_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img'),
        ),
    ]
