# Generated by Django 3.1.4 on 2020-12-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0018_auto_20201210_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('in_link', models.URLField(blank=True)),
                ('fb_link', models.URLField(blank=True)),
                ('ln_link', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(upload_to='members/images')),
            ],
        ),
        migrations.CreateModel(
            name='Member2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('in_link', models.URLField(blank=True)),
                ('fb_link', models.URLField(blank=True)),
                ('ln_link', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(upload_to='members/images')),
            ],
        ),
        migrations.CreateModel(
            name='Member3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('in_link', models.URLField(blank=True)),
                ('fb_link', models.URLField(blank=True)),
                ('ln_link', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(upload_to='members/images')),
            ],
        ),
        migrations.CreateModel(
            name='Member4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('in_link', models.URLField(blank=True)),
                ('fb_link', models.URLField(blank=True)),
                ('ln_link', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(upload_to='members/images')),
                ('post', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
