# Generated by Django 3.1.4 on 2020-12-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thereg', '0019_auto_20201210_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member1',
            name='image',
            field=models.ImageField(upload_to='members/first/images'),
        ),
        migrations.AlterField(
            model_name='member2',
            name='image',
            field=models.ImageField(upload_to='members/second/images'),
        ),
        migrations.AlterField(
            model_name='member3',
            name='image',
            field=models.ImageField(upload_to='members/third/images'),
        ),
        migrations.AlterField(
            model_name='member4',
            name='image',
            field=models.ImageField(upload_to='members/fourth/images'),
        ),
    ]
